apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lyna-sovann0964-nginx-timeout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/lyna-sovann0964-nginx-timeout.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: lyna-sovann0964-nginx-timeout
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
